# Generated by Django 4.2.5 on 2024-11-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'managed': True},
        ),
    ]
