# Generated by Django 4.2.5 on 2024-11-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0003_estudiante_user_profesor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asocia',
            options={},
        ),
    ]
