# Generated by Django 4.2.5 on 2024-11-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0004_alter_asocia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asocia',
            options={'managed': False},
        ),
    ]
