# Generated by Django 4.2.5 on 2024-11-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0005_alter_asocia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evalua',
            options={'managed': True},
        ),
    ]
