# Generated by Django 4.2.5 on 2024-11-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0006_alter_evalua_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evalua',
            options={'managed': False},
        ),
    ]
