# Generated by Django 4.2.5 on 2024-11-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0007_alter_evalua_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evalua',
            options={'managed': True},
        ),
    ]
