# Generated by Django 4.2.5 on 2024-11-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0008_alter_evalua_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evalua',
            options={'managed': False},
        ),
    ]
