# Generated by Django 4.2.5 on 2024-11-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0009_alter_evalua_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responde',
            options={'managed': True},
        ),
    ]
