# Generated by Django 4.2.5 on 2024-11-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0013_alter_responde_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responde',
            options={'managed': True},
        ),
    ]
